name: repo

on:
  schedule:
    - cron: "0 15 * * 2"
  workflow_dispatch:

jobs:
  pre-commit-autoupdate:
    name: pre-commit autoupdate
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/commaai/panda:latest
    steps:
    - uses: actions/checkout@v3
    - name: pre-commit autoupdate
      run: |
        git config --global --add safe.directory '*'
        pre-commit autoupdate
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@2b17eaf819f0c76d6ff27bd4c6a97eea23b82b95
      with:
        token: ${{ secrets.ACTIONS_CREATE_PR_PAT }}
        commit-message: Update pre-commit hook versions
        title: 'pre-commit: autoupdate hooks'
        branch: pre-commit-updates
        base: master
        delete-branch: true
